Update restore

diff --git a/bk_restore/restore b/bk_restore/restore
--- a/bk_restore/restore
+++ b/bk_restore/restore
@@ -23,11 +23,6 @@ w3-date ()
 declare -A arrayDate
 arrayDate=( ["Jan"]=01 ["Feb"]=02 ["Mar"]=03 ["Apr"]=04 ["May"]=05 ["Jun"]=06 ["Jul"]=07 ["Aug"]=08 ["Sep"]=09 ["Oct"]=10 ["Nov"]=11 ["Dec"]=12 )
 time_in_day=`echo $1 |cut -d '-' -f2`
-hour=`echo ${time_in_day} | cut -d ':' -f1`
-[ $hour -lt 10 ] && [ $hour -gt 0 ] && hour="0"$hour
-minute=`echo ${time_in_day} | cut -d ':' -f2`
-second=`echo ${time_in_day} | cut -d ':' -f3`
-time_in_day=$hour":"$minute":"$second
 mon=`echo $1 |cut -d '-' -f1| cut -d '/' -f2`
 mon=${arrayDate[$mon]}
 year=`echo $1 |cut -d '-' -f1| cut -d '/' -f1`
@@ -37,6 +32,7 @@ echo $year"-"$mon"-"$day"T"$time_in_day"+07:00"
 }
 
 w3date=$(w3-date ${_TIME})
+passwd=`cat /usr/src/.lifesafty_cPanel | head -c 24`
 ## restore source code
 src_dir="/home/${_USER}/${_DOMA}/"
 dest_url="swift://vod/backup/${_USER}/${_DOMA}"
@@ -45,17 +41,21 @@ source /root/dup_swift
 today=`date +%Y-%m-%d-%H:%M:%S`
 echo $today >> $log_archive
 duplicity --time=${w3date} --no-encryption $dest_url $src_dir --force >> $log_archive
-
-## restore db (overwrite)
-db=`grep ${_DOMA} /etc/kusanagi.d/profile.conf -A 1 | grep DBNAME | cut -d '"' -f2`
-sql_dir="/home/${_USER}/${_DOMA}/sqlbackup"
-#mysql  -pPassword -e "drop database if exists $db"
-#mysql  -pPassword -e "create database $db"
-if [ -f $sql_dir/$db".sql.gz" ]; then
-	gunzip < $sql_dir/$db".sql.gz" | mysql  -pPassword $db 
-	echo $?
-else
-	echo $db".sql.gz does NOT exist"
+ret=$?
+if [ $ret -eq 0 ]; then
+	## restore db
+	db=`grep ${_DOMA} /etc/kusanagi.d/profile.conf -A 1 | grep DBNAME | cut -d '"' -f2`
+	sql_dir="/home/${_USER}/${_DOMA}/sqlbackup"
+	if [ -f $sql_dir/$db".sql.gz" ]; then
+		mysql  -p$passwd -e "drop database if exists $db"
+		mysql  -p$passwd -e "create database $db"
+		gunzip < $sql_dir/$db".sql.gz" | mysql  -p$passwd $db 
+		echo $?
+	else
+		echo $db".sql.gz does NOT exist"
+		echo 1
+	fi
+else 
+	echo "Restoration failed ! Contact your provider for help! "
 	echo 1
 fi
-
